### ISSUE TITLE
Demo website

### ISSUE THREAD

**Issue by pavelloz** [BlinkID/blinkid-in-browser#110]
Hello,

I noticed that your [demo page](https://demo.microblink.com/in-browser-sdk/blinkid/) is using 6.0.1 version which is not the newest. Could you please update it to the newest version?

**Comment by AngTim** [comment]
Hello Pavel,

Thank you for noticing.
Our demo application has been updated and has a new look, so feel free to check it out on the link [https://demo.microblink.com/blinkid-extract](url) and you can also test on one of our examples in the GitHub repository [https://blinkid.github.io/blinkid-in-browser/examples/multi-side/javascript/index.html](url).

Both applications are now running the latest version of the SDK (6.2.1). 

Let us know if there is anything else we can assist you with.

Kind regards,
Angelo
Microblink LTD

**Comment by pavelloz** [comment]
Thank you!
