### ISSUE TITLE
Server permission payload is corrupted!

### ISSUE THREAD

**Issue by mircogrosch** [BlinkID/blinkid-in-browser#114]
Hi, I have the following issue. By starting the sdk with a correct licence and add engineLocation. I get error with the following message "Server permission payload is corrupted! "

`
if (!BlinkIDSDK.current.isBrowserSupported()) {
            setStep(validationStep.ERROR);
            return;
        }

        const licenseKey = process.env.NEXT_PUBLIC_LICENCE_MICROBLINK;

        const loadSettings = new BlinkIDSDK.current.WasmSDKLoadSettings(
            licenseKey
        );
     

         loadSettings.engineLocation = window.location.origin + "/resources";

        BlinkIDSDK.current.loadWasmModule(loadSettings).then(
            (sdkInstance) => {
                startScan(sdkInstance);
            },
            (error) => {
                setStep(validationStep.ERROR);
                console.error("Error SDK!", error);
            }
        );
`

Applying  React/Next js

**Comment by AngTim** [comment]
The case was continued via the support ticket

**Comment by batheleuz** [comment]
Hello 
I am having the same issue.

Please can you help ?

**Comment by mircogrosch** [comment]
Hi, please contact support. They helped me solve the problem (support@microblink.com)

**Comment by AngTim** [comment]
Hi Batheleuz,

as @mircogrosch mentioned, please contact us at [support@microblink.com](mailto:support@microblink.com)) and please let us know the license number you are using in the e-mail so we can assist you with the issue further.

Kind regards,
Angelo
Microblink LTD
