### ISSUE TITLE
VideoRecognizer recognize function recognitionTimeoutMs parameter is not working.

### ISSUE THREAD

**Issue by nurlan-vyyer** [BlinkID/blinkid-in-browser#116]
I use this:
`const processResult = await barcodeVideoRecognizer.recognize()`
and it works fine.

Tried
`const processResult = await barcodeVideoRecognizer.recognize(10000)`
anticipating it will stop recognition after 10 seconds, but nothing happens.
I think it should resolve with empty result, but it doesn't work.

Docs say:
`(property) VideoRecognizer.recognize: (recognitionTimeoutMs?: number | undefined) => Promise<BlinkIDSDK.RecognizerResultState>`
@param recognitionTimeoutMs
Amount of time in ms that the recognizer will stay in the Uncertain state before resolving.

**Comment by AngTim** [comment]
Hello Nurlan,

Thank you for the report.
As the timeout is usually set for the VideoRecognizer as a separate class [https://github.com/BlinkID/blinkid-in-browser/blob/5168010cceb82f1d7b7d951104bda5027f16d06a/src/MicroblinkSDK/VideoRecognizer.ts#L54]() 
which can be configured for a custom recognition timeout with the examples on the following links:

[https://gist.github.com/vjekoart/82ff38680b4c7c700a09653fbfd07391](url)
[https://gist.github.com/vjekoart/148ed8868ed738bdf8e8cb8fdfa87320](url)

Please check the mentioned documentation and let us know if you have any questions.

Kind regards,
Angelo
Microblink LTD
