### ISSUE TITLE
Scan Identity Document both sides using Image file

### ISSUE THREAD

**Issue by pjain8889** [BlinkID/blinkid-in-browser#14]
I have checked the live examples mentioned in the below link and it is awesome!

https://github.com/BlinkID/blinkid-in-browser

Is it possible to scan the identity document from both sides from image file.

Can you please add one more live example, how we can scan the identity document from both sides from image file.

let me know if I am missing something.

Thanks in Advance!

**Comment by vjekoart** [comment]
Hi @pjain8889,

It's not possible to scan both sides of the identity document from image file. Currently, this is not a planned feature, but this may change over time.
