### ISSUE TITLE
Way to get scan image URL

### ISSUE THREAD

**Issue by pjain8889** [BlinkID/blinkid-in-browser#15]
Is there any way to get the scan image url when scan through webcam.

Please help.

**Comment by vjekoart** [comment]
Hi @pjain8889,

It's possible to obtain image from which data was extracted. To achieve that it's required to use `SuccessFrameGrabber`. You can find related examples for this functionality in folder [examples/success-frame-grabber](https://github.com/BlinkID/blinkid-in-browser/tree/master/examples/success-frame-grabber).
