### ISSUE TITLE
need functionality to take picture from webcam and save it

### ISSUE THREAD

**Issue by pjain8889** [BlinkID/blinkid-in-browser#16]
I want to develop the webcam functionality the same as shown in the below link.

https://microblink.com/products/blinkcard/web-api

Where I can click picture from the webcam and also save the image of the document which is scanned.
From where I can get the code?

Please help me.

Thanks in Advance.

**Comment by vjekoart** [comment]
Hi @pjain8889,

You can get image of the scanned document by enabling recognizer option `returnFullDocumentImage`. This option is available for `BlinkIDRecognizer` and `BlinkIDCombinedRecognizer`.

Here's an example on how to create a recognizer with aforementioned setting:

```javascript
const genericIDRecognizer = await BlinkIDSDK.createBlinkIdRecognizer(sdk);
const recognizerSettings = await genericIDRecognizer.currentSettings();

recognizerSettings.returnFullDocumentImage = true;

await genericIDRecognizer.updateSettings(recognizerSettings);
```

This code snippet works well with the provided [blinkid-camera](https://github.com/BlinkID/blinkid-in-browser/blob/master/examples/blinkid-camera/javascript/app.js) example.

Also, is this question related with [this issue](https://github.com/BlinkID/blinkid-in-browser/issues/15)? If so, I can close the old one.

Sincerely,
Vjekoslav

**Comment by vjekoart** [comment]
Hi @pjain8889,

Just wondering have you managed to extract image of scanned document?

Sincerely,
Vjekoslav
