### ISSUE TITLE
way to check device have camera or not

### ISSUE THREAD

**Issue by pjain8889** [BlinkID/blinkid-in-browser#19]
Is there any way to find out the device have webcam/camera when we initialize the SDK so that we can show the camera button disabled.

Let me know if you need more info.

Thanks!

**Comment by vjekoart** [comment]
Hi @pjain8889,

We've implemented mechanism to check if any kind of video device is available in the UI component.

You can reuse the code to implement logic on your side, or you can use the UI component.

The function you can reuse is called `hasVideoDevices` and is defined in [device.helpers.ts](https://github.com/BlinkID/blinkid-in-browser/blob/master/ui/src/utils/device.helpers.ts#L3) file.

Hope this helps.

Sincerely,
Vjekoslav
