### ISSUE TITLE
Any way to extract data for specific document we passed

### ISSUE THREAD

**Issue by pjain8889** [BlinkID/blinkid-in-browser#21]
Is there any way to handle the extract data for the specific document we passed.

Suppose user select a passport from the dropdown and then he will be able to extract data for a passport only. If he uploads the driver`s licence then it shows some error which says to upload a passport only.
Any support for this type of issue?

Thanks in Advance!

Thanks,
Prashant

**Comment by pjain8889** [comment]
Any way to get the document type in the extracted data?

**Comment by vjekoart** [comment]
Hi @pjain8889,

Scan results have a property called `classInfo`. This object contains information about the document that has been scanned.

Based on the value of that property, it's possible to inform the user if the wrong type of document has been provided. Also, it's not possible to know document type before scan action is completed.

It's possible to see a complete list of possible options for `classInfo` property in related [ClassInfo.ts](https://github.com/BlinkID/blinkid-in-browser/blob/master/src/Recognizers/BlinkID/Generic/ClassInfo.ts) file.

Sincerely,
Vjekoslav

**Comment by pjain8889** [comment]
Hi @vjekoart 

I upload a passport to extract the information but I did not get document type correct after extraction. See below image

![image](https://user-images.githubusercontent.com/67706842/98266741-a8b3e880-1fb0-11eb-8108-4eb5b5779a2a.png)

Let me know If I am missing something

**Comment by vjekoart** [comment]
Hi @pjain8889,

I did some research and in the current version information about passport is not added to `classInfo` property. This is desired behaviour, even though it will change in the future versions where `classInfo` will be properly filled.

However, it's still possible to detect if user has scanned a passport. This information is available in the `mrz` property in the recognition results. Useful fields are `mrz.documentCode` and `mrz.issuer`. The former should have a value of `"PS"` for passports, while the latter has the information about the issuer country.

Hope this helps.

Sincerely,
Vjekoslav

**Comment by pjain8889** [comment]
Hi @vjekoart,

Thanks for the info.

In the extracted data, the mrz.documentCode is P< but not the "PS" as you mentioned in the above comment. See below screenshot.

![image](https://user-images.githubusercontent.com/67706842/98586213-6bbc5e80-22ee-11eb-9beb-bf95f1ebc223.png)
 

Can you please confirm what should be the value of the **mrz.documentCode** when document is a passport.

**Comment by vjekoart** [comment]
Hi @pjain8889,

Just to correct myself, only the first character in the MRZ defines document type. Which means that the `mrz.documentCode` property must start with a `P` character if the document type is a passport.

Second character represents a passport type which is not standardized, but rather it depends on the issuer.

Source: https://en.wikipedia.org/wiki/Machine-readable_passport

**Comment by pjain8889** [comment]
Hi @vjekoart ,

One of the DL is not getting extracted but the docType is NONE. so how can we identify whether extraction is failed. Is there any way to check whether the extraction is failed or passed?
See attached images.
Let me know if you have any questions!

![USA DL Front (3)](https://user-images.githubusercontent.com/67706842/103029381-b254d800-457f-11eb-8052-1dd2d6140071.jpg)


![USA DL back (3)](https://user-images.githubusercontent.com/67706842/103029369-abc66080-457f-11eb-8cba-7cf5049699ae.jpg)

I am getting the response like this(See file):
[reponse.txt](https://github.com/BlinkID/blinkid-in-browser/files/5736734/reponse.txt)

Thanks,
Prashant Jain

**Comment by vjekoart** [comment]
Hi @pjain8889,

It looks like the attached file contains response from **BlinkID Cloud API** or **BlinkID Self-hosted API** services.

These are different products, and we cannot help you with that problem here since this repository is only related to the **BlinkID In-browser SDK**.

I would advise you to contact our support team at [support@microblink.com](mailto:support@microblink.com).

P.S.
I'm going to remove images of identity document from your comment since that is pretty sensitive data. That is also one of the reasons why I would advise you to contact our support team via email, so they can inform you about the safe exchange of sensitive data.

**Comment by pjain8889** [comment]
Thanks @vjekoart.
