### ISSUE TITLE
How can I upload a PDF file to a 

### ISSUE THREAD

**Issue by Shubhamp777** [BlinkID/blinkid-in-browser#22]
const imageFrame = BlinkIDSDK.captureFrame( imageElement );
const processResult = await recognizerRunner.processImage( imageFrame );
  const recognitionResult = await recognizer.getResult();

ImageElment is a html image element .

But here I want to upload a pdf file to BlinkIDSDK.  

Could you please tell me please. How can I pass a pdf file here to BlinkIDSDK.?

Thanks,
Shubham

**Comment by vjekoart** [comment]
Hello @Shubhamp777,

It's not possible to upload a PDF file to SDK, it only works with image frame.

**Comment by Shubhamp777** [comment]
Ohh okay ):  , 

 Thanks for the update .
