### ISSUE TITLE
Getting failed key error even domain and key is correct

### ISSUE THREAD

**Issue by pjain8889** [BlinkID/blinkid-in-browser#25]
Hi,

I am getting the below error:
![image](https://user-images.githubusercontent.com/67706842/99429519-24595200-292e-11eb-9745-38ea0c2d8e49.png)

I am using the correct key and domain but still getting error.

Can you please help me to find the issue here?

Thanks in advance

Thanks,
Prashant Jain

**Comment by pjain8889** [comment]
Hi, 
Any update on above query?

Thanks,
Prashant Jain

**Comment by vjekoart** [comment]
Hi @pjain8889,

Sorry for the delayed response.

It looks like the license key requires an online validation which did not happen. Since this is a problem with license key, I would suggest that you contact our support at [help.microblink.com](http://help.microblink.com/).
