### ISSUE TITLE
SuccessFrameGrabber on BlinkIDCombined

### ISSUE THREAD

**Issue by kinesthai** [BlinkID/blinkid-in-browser#26]
I'm having trouble figuring out how I can use the `SuccessFrameGrabberRecognizer` and BlinkIDCombined. 

On the Example provided on your documentation it only uses BlinkID (scanning just one side of the ID). 
How can I extract the images from both sides of the document?

**Comment by vjekoart** [comment]
Hi @kinesthai,

It's not possible to extract images from both sides of the document by using `SuccessFrameGrabberRecognizer`. In case of BlinkIDCombined, it will only return an image of the back side of the document.

If back side of a document is enough, you can use `SuccessFrameGrabberRecognizer` in combination with BlinkIDCombined. Procedure is same as in the provided example.

```javascript
// Create recognizer and related SuccessFrameGrabber recognizer
const combinedGenericIDRecognizer = await BlinkIDSDK.createBlinkIdCombinedRecognizer( sdk );
const sfgRecognizer = await BlinkIDSDK.createSuccessFrameGrabberRecognizer( sdk, combinedGenericIDRecognizer );

...

// Create instance of RecognizerRunner with SFG recognizer
const recognizerRunner = await BlinkIDSDK.createRecognizerRunner
(
    // SDK instance to use
    sdk,
    // List of recognizer objects that will be associated with created RecognizerRunner object
    [ sfgRecognizer ],
    // [OPTIONAL] Should recognition pipeline stop as soon as first recognizer in chain finished recognition
    false,
    // Callbacks object that will receive recognition events
    callbacks
);

...

// Retrieve results of SuccessFrameGrabberRecognizer
const sfgResults = await sfgRecognizer.getResult();
if ( sfgResults.state !== BlinkIDSDK.RecognizerResultState.Empty )
{
    console.log( "Success back-side frame for BlinkIDCombinedRecognizer", sfgResults );
}
```
