### ISSUE TITLE
Not working on iOS lower than 14

### ISSUE THREAD

**Issue by kinesthai** [BlinkID/blinkid-in-browser#27]
WASM is supported by iOS since version 11 but blinkid-in-browser doesn't work on any version lower than iOS14.

**Comment by vjekoart** [comment]
Hi @kinesthai,

Thank you for the information. We're going to check the behaviour of BlinkID In-browser SDK on devices with iOS 13 and lower and report the conclusion here.

**Comment by vjekoart** [comment]
We're currently developing a solution for this problem.

When the relevant version of the SDK will be published, it will be referenced in this issue.

**Comment by vjekoart** [comment]
This issue has been solved with the release of [BlinkID 5.11.0](https://github.com/BlinkID/blinkid-in-browser/releases/tag/v5.11.0).
