### ISSUE TITLE
Provided translations public API to replace existing is not working as expected

### ISSUE THREAD

**Issue by mariusvirb** [BlinkID/blinkid-in-browser#32]
Hello, good people,

We're using prebuilt UI web component, but I've come across a piece of code that does not work as expected in our project.

The `blinkid-in-browser` web component accepts a property called `translations` which in theory should replace `defaultTranslations` in `translations.service.ts`, which should accept both `string` and `string[]`.

The implementation for the `TranslationsService` is the following:
```
constructor(alternativeTranslations?: { [key: string]: string|Array<string> }) {
    this.translations = defaultTranslations;

    for (const key in alternativeTranslations) {
      if (typeof this.translations[key] === 'string') {
        this.translations[key] = alternativeTranslations[key];
      }
    }
  }
```
The reality is - 2 default keys are **never** overwritten (`camera-feedback-scan-front` and `camera-feedback-scan-back`) because the condition is never met with `string[]` type.

Our usage sample is as per docs:
```
<script>
  // select web component DOM node
  el.licenceKey = ...
  // all other config
  el.translations = { 'camera-feedback-scan-front': 'This is never replaced with defaults' }
</script>
```

We have tried using `rawTranslations` api, but it is the same result and when looking at the source code, I think it is never utilised at all? But please don't take my word for it, it is only what I understood from a piece of code in `blinkid-in-browser.tsx:287` in `componenWillRender` because `this.translations` will always be available since at least they will have assigned `defaultTranslations` from `TranslationService` instance ?

Best regards,

**Comment by vjekoart** [comment]
Hello @mariusvirb,

Thank you for the report. We've identified this problem during the development of the latest BlinkID 5.10 version.

Please try to use the same mechanism to define alternative translations with the UI component from the latest version.

Sincerely,
Vjekoslav

**Comment by mariusvirb** [comment]
Hey, @vjekoart, thank you very much! Will try it out tomorrow and let you know :pray: 

For now closing the issue :v:

**Comment by mariusvirb** [comment]
Just letting you know @vjekoart translation service works now as expected :rocket:
