### ISSUE TITLE
Make VideoRecognizer public

### ISSUE THREAD

**Issue by sveres** [BlinkID/blinkid-in-browser#34]
Currently VideoRecognizer class is exported, but it's constructor is private
see `private constructor();` in `/node_modules/@microblink/blinkid-in-browser-sdk/types/MicroblinkSDK/VideoRecognizer.d.ts`

Is there a specific reason for not exposing it?

During the initial implementation we somehow missed that the `createVideoRecognizerFromCameraStream` actually requests a stream and sets it as a src for the video. While I see why this feature can have benefit for other users, in our case we already manage that part, and we need to and want to build on top of that.

To me it seams this functionality (where the implementation's responsibility is to handle the stream is already there in the  VideoRecognizer.  We can construct it simply with a video and the recognizeRunner.

We would like to request a change, which makes the VideoRecognizer publicly available.

**Comment by vjekoart** [comment]
Hi @sveres,

Thank you for the report. I see no reason why we shouldn't make the VideoRecognizer publicly available.

We're going to add this change to the upcoming bugfix release for BlinkID In-browser, which should happen next week.

Once the modified version of VideoRecognizer class is publicly available, I will post an update here.

Sincerely,
Vjekoslav

**Comment by sveres** [comment]
Hi @vjekoart,
Great news, thanks for the quick reply and solution!

**Comment by sveres** [comment]
Hi @vjekoart,
Is there any update on the release?

**Comment by sveres** [comment]
No worries, we have all been there :) Thank you for the update!

**Comment by sveres** [comment]
@vjekoart is it possible that this change didn't make it to this release or am I missing something?
https://github.com/BlinkID/blinkid-in-browser/blob/b0e33d8e51f03a321b803ea5291b72e21894e58b/src/MicroblinkSDK/VideoRecognizer.ts#L510

**Comment by vjekoart** [comment]
@sveres Latest bugfix release was a hotfix for a client which is using UI component in production. Since we did that hotfix directly in this repository, we could not include other improvements, including changes to VideoRecognizer class.

I'm aware that we're delaying this quite simple change, but we're waiting to properly implement a solution for #27 which should be published with the same version.

**Comment by vjekoart** [comment]
Hi @sveres,

We've released a hotfix version 5.10.2 which includes a private constructor of `VideoRecognizer` class.

Our initial plan was to release this modification alongside other various improvements, but there were unexpected development delays. Sorry for the delay.

Sincerely,
Vjekoslav
