### ISSUE TITLE
Better support for styling using shadow dom css part pseudo element

### ISSUE THREAD

**Issue by vladop** [BlinkID/blinkid-in-browser#35]
Currently, the only way to change styling is by overriding some predefined variables which I found somewhat limited.
I came across this CSS pseudoelement https://css-tricks.com/styling-in-the-shadow-dom-with-css-shadow-parts/ where you expose
some parts of shadow dom which can be styled. Then shadow DOM elements could be styled from "parent".
What do you think about this?

**Comment by vjekoart** [comment]
Hi @vladop,

Thanks for the suggestion. This looks great and we will definitely look to add support for `::part` selector in the upcoming release.

Sincerely,
Vjekoslav

**Comment by vjekoart** [comment]
Hi @vladop,

We've added support for `::part` selector with the v5.14.1.

Sincerely,
Vjekoslav
