### ISSUE TITLE
SuccessFrameGrabber with UI blinkid-in-browser web component

### ISSUE THREAD

**Issue by yeisonmejia** [BlinkID/blinkid-in-browser#38]
Hi!

I'm having trouble figuring out how I can use the SuccessFrameGrabberRecognizer in the UI web component.

I couldn't find an example of that in your documentation. Can I use SuccessFrameGrabber within the UI web component?

<SuccessFrameGrabber ... recognizers="SuccessFrameGrabberRecognizer"></SuccessFrameGrabber> dosen't work.

**Comment by vjekoart** [comment]
Hi @yeisonmejia,

It's possible to enable `SuccessFrameGrabber` when using the UI component.

To do that, one can use `include-success-frame` attribute in the following manner:

```html
<blinkid-in-browser license-key="..." include-success-frame="true" ...></blinkid-in-browser>
```

There is automatically generated documentation with all UI component options located [here](https://github.com/BlinkID/blinkid-in-browser/tree/master/ui/docs/components/blinkid-in-browser). Although, it looks like we could be more transparent about where documentation is located and what are the possibilities. We'll try to improve that with the future releases :)

Let me know if this has solved your issue.

Sincerely,
Vjekoslav

**Comment by yeisonmejia** [comment]
Great! that is what I was looking for, thanks!

I saw in the response that fullDocumentBackImage and fullDocumentFrontImage objects were present when the component use BlinkIdCombinedRecognizer. That's means I can get an image from both sides of a document, correct? how can I  know which documents support both side's scans? I made some tests and I've gotten fullDocumentBackImage empty.

```html
<blinkid-in-browser
    license-key="..."
    engine-location="https://unpkg.com/@microblink/blinkid-in-browser-sdk/resources/"
    recognizers="BlinkIdCombinedRecognizer"
    recognizer-options="returnFullDocumentImage,returnFaceImage"
></blinkid-in-browser>
```

**Comment by vjekoart** [comment]
You're correct. It's possible to get an image from both sides of a document for specific documents.

For the full list of supported documents with information if both sides are supported, check out the [BlinkIDRecognizer](https://github.com/BlinkID/blinkid-in-browser/blob/master/docs/BlinkIDRecognizer.md) document.

**Comment by yeisonmejia** [comment]
Excellent! I was trying with a Colombian document but were difficult for SDK to recognize the backside. Today I'm trying again and it works.

Thanks!!
