### ISSUE TITLE
The live version demo no longer works

### ISSUE THREAD

**Issue by skyrex-mark** [BlinkID/blinkid-in-browser#4]
https://blinkid.github.io/blinkid-in-browser/examples/umd/index.html
```
Uncaught ReferenceError: BlinkIDSDK is not defined
    at index.html:45
```

**Comment by vjekoart** [comment]
Hi @skyrex-mark,

Thank you for the feedback, we're aware of the problem and we're going to publish a fix as soon as possible.

**Comment by vjekoart** [comment]
We have added additional live example apps to provide more clarity regarding integration and now they're working as expected.

1. [Scan front side of identity document from web camera](https://blinkid.github.io/blinkid-in-browser/examples/blinkid-camera/javascript/index.html)
2. [Scan front side of identity document from image file](https://blinkid.github.io/blinkid-in-browser/examples/blinkid-file/javascript/index.html)
3. [Scan both sides of identity document from web camera](https://blinkid.github.io/blinkid-in-browser/examples/combined/javascript/index.html)
4. [Scan barcode from identity document from web camera](https://blinkid.github.io/blinkid-in-browser/examples/idbarcode/javascript/index.html)

**Comment by skyrex-mark** [comment]
This is awesome! Thank you for the updates!

**Comment by pjain8889** [comment]
Hello @vjekoart,

I have checked the live examples( mentioned above ) and it is awesome!

Is it possible to scan the identity document from both sides from image file.

Can you please add one more live example, how we can scan the identity document from both sides from image file.

let me know if I am missing something.
Thanks in Advance!
