### ISSUE TITLE
Unable to load SDK from unpkg

### ISSUE THREAD

**Issue by SolarKing** [BlinkID/blinkid-in-browser#42]
Hi all,

We are currently running into a production issue and we are doing some troubleshooting steps on our end and have ran to various issues. I'm posting what would be our ideal setup, the issues around it, and hoping to see if we can get some help troubleshooting this issue.

We put the Expected / Actual sections of this issue up here for brevity, but please see the Details / Additional Context to know more about our scenario.

## Expected Behavior

- Ideally we would like to be using the latest sdk: `5.11.1`, but any version is fine
- Pointing the `engine-location` to unpkg should work just fine, as it has done so previously

## Actual Behavior

We run into the following issues when the component is mounted:

JSX just for reference

```
const engineLocation = "https://unpkg.com/@microblink/blinkid-in-browser-sdk@5.11.1/resources"
...
<blinkid-in-browser
       ref={blinkId}
       license-key={licenseKey}
       recognizers="BlinkIdRecognizer"
       engine-location={engineLocation}
       include-success-frame={true}
       recognizer-options="returnFullDocumentImage, returnFaceImage"
 ></blinkid-in-browser>
```

Errors: 

```
index.js:1 fatalError 
CustomEvent {isTrusted: false, detail: EventFatalError, type: "fatalError", target: blinkid-in-browser.hydrated, currentTarget: blinkid-in-browser.hydrated, …}
bubbles: true
cancelBubble: false
cancelable: true
composed: true
currentTarget: null
defaultPrevented: false
detail: EventFatalError {code: "SDK_LOAD_FAILED", message: "Failed to load SDK!", details: "Problem during initialization of worker file!"}
eventPhase: 0
isTrusted: false
path: (18) [mb-component.hydrated, slot, document-fragment, mb-container.hydrated, document-fragment, blinkid-in-browser.hydrated, div.css-1glq2si, div.css-1b3s1y3, div.css-pg23ef, div.css-1dlftso, div.css-1472lk3, main.css-0, div.css-15q7f2c, div#root, body, html.hydrated, document, Window]
returnValue: true
srcElement: blinkid-in-browser.hydrated
target: blinkid-in-browser.hydrated
timeStamp: 71938.78499994753
type: "fatalError"
__proto__: CustomEvent
```

```
BlinkIDWasmSDK.js:45 Uncaught DOMException: Failed to construct 'Worker': Script at 'https://unpkg.com/@microblink/blinkid-in-browser-sdk@5.11.1/resources/advanced-threads/BlinkIDWasmSDK.worker.js' cannot be accessed from origin 'https://drivers.dev.getcheckapp.com'.
    at Object.Fd (https://unpkg.com/@microblink/blinkid-in-browser-sdk@5.11.1/resources/advanced-threads/BlinkIDWasmSDK.js:45:42)
    at Object.Ud (https://unpkg.com/@microblink/blinkid-in-browser-sdk@5.11.1/resources/advanced-threads/BlinkIDWasmSDK.js:45:91)
    at Gb (https://unpkg.com/@microblink/blinkid-in-browser-sdk@5.11.1/resources/advanced-threads/BlinkIDWasmSDK.js:144:120)
    at _ (https://unpkg.com/@microblink/blinkid-in-browser-sdk@5.11.1/resources/advanced-threads/BlinkIDWasmSDK.js:194:280)
    at https://unpkg.com/@microblink/blinkid-in-browser-sdk@5.11.1/resources/advanced-threads/BlinkIDWasmSDK.wasm:wasm-function[4380]:0xc8df4
    at https://unpkg.com/@microblink/blinkid-in-browser-sdk@5.11.1/resources/advanced-threads/BlinkIDWasmSDK.wasm:wasm-function[4383]:0xc8fa9
    at https://unpkg.com/@microblink/blinkid-in-browser-sdk@5.11.1/resources/advanced-threads/BlinkIDWasmSDK.wasm:wasm-function[4385]:0xc90c2
    at Xa (https://unpkg.com/@microblink/blinkid-in-browser-sdk@5.11.1/resources/advanced-threads/BlinkIDWasmSDK.wasm:wasm-function[3882]:0xb0570)
    at E.___wasm_call_ctors (https://unpkg.com/@microblink/blinkid-in-browser-sdk@5.11.1/resources/advanced-threads/BlinkIDWasmSDK.js:197:81)
    at Sd (https://unpkg.com/@microblink/blinkid-in-browser-sdk@5.11.1/resources/advanced-threads/BlinkIDWasmSDK.js:31:95)
```

## Specifications

Package Version: `@microblink/blinkid-in-browser-sdk": "5.11.1"`
Platform: Typescript React (CRA / react-scripts)

## Details / Additional Context

- Initially we had the package version at `^5.8.1` but we were pointing our `engine-location` at `https://unpkg.com/@microblink/blinkid-in-browser-sdk/resources/` (note: the lack of version locking within the url, so it probably just points to latest) -  everything was working perfectly fine.
- Our team is guessing at some point, the latest version got bumped and was being served to the 5.8.1 component, thus causing the blinkid-in-browser component to crash.
- We moved the resources locally within the public folder, pointed to engine-location to `/resources`, but ran into some errors (failed to capture them, will reproduce momentarily)
- We then pointed the url to engine to `https://unpkg.com/@microblink/blinkid-in-browser-sdk@5.8.1/resources` and we ran into the following errors:
```
home/charlesbido/Documents/projects/check-app/node_modules/@microblink/blinkid-in-browser-sdk/ui/dist/esm-es5/blinkid-in-browser_10.entry.js
SyntaxError: /home/charlesbido/Documents/projects/check-app/node_modules/@microblink/blinkid-in-browser-sdk/ui/dist/esm-es5/blinkid-in-browser_10.entry.js: Identifier '__awaiter' has already been declared (609:9)

  607 | PERFORMANCE OF THIS SOFTWARE.
  608 | ***************************************************************************** */
> 609 | function __awaiter(thisArg, _arguments, P, generator) {
      |          ^
  610 |     function adopt(value) {
  611 |         return value instanceof P ? value : new P(function (resolve) {
  612 |             resolve(value);
printWarnings @ webpackHotDevClient.js:138
handleWarnings @ webpackHotDevClient.js:143
push.../../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:210

```
```
Error: Module build failed (from /home/charlesbido/Documents/projects/check-app/node_modules/react-scripts/node_modules/babel-loader/lib/index.js):
SyntaxError: /home/charlesbido/Documents/projects/check-app/node_modules/@microblink/blinkid-in-browser-sdk/ui/dist/esm-es5/blinkid-in-browser_10.entry.js: Identifier '__awaiter' has already been declared (609:9)

  607 | PERFORMANCE OF THIS SOFTWARE.
  608 | ***************************************************************************** */
> 609 | function __awaiter(thisArg, _arguments, P, generator) {
      |          ^
  610 |     function adopt(value) {
  611 |         return value instanceof P ? value : new P(function (resolve) {
  612 |             resolve(value);
    at Parser._raise (home/charlesbido/Documents/projects/check-app/node_modules/@babel/parser/lib/index.js:748)
    at Parser.raiseWithData (home/charlesbido/Documents/projects/check-app/node_modules/@babel/parser/lib/index.js:741)
    at Parser.raise (home/charlesbido/Documents/projects/check-app/node_modules/@babel/parser/lib/index.js:735)
    at ScopeHandler.checkRedeclarationInScope (home/charlesbido/Documents/projects/check-app/node_modules/@babel/parser/lib/index.js:4919)
    at ScopeHandler.declareName (home/charlesbido/Documents/projects/check-app/node_modules/@babel/parser/lib/index.js:4885)
    at Parser.registerFunctionStatementId (home/charlesbido/Documents/projects/check-app/node_modules/@babel/parser/lib/index.js:12417)
    at Parser.parseFunction (home/charlesbido/Documents/projects/check-app/node_modules/@babel/parser/lib/index.js:12397)
    at Parser.parseFunctionStatement (home/charlesbido/Documents/projects/check-app/node_modules/@babel/parser/lib/index.js:12024)
    at Parser.parseStatementContent (home/charlesbido/Documents/projects/check-app/node_modules/@babel/parser/lib/index.js:11714)
    at Parser.parseStatement (home/charlesbido/Documents/projects/check-app/node_modules/@babel/parser/lib/index.js:11676)
    at Object.../../node_modules/@microblink/blinkid-in-browser-sdk/ui/dist/esm-es5/blinkid-in-browser_10.entry.js (2.chunk.js:10)
    at __webpack_require__ (bootstrap:856)
    at fn (bootstrap:150)
    at Function.fn.t (bootstrap:194)
    at  groupOptions: {} namespace object:18
```
```
index-cb5c04e4.js:1310 Uncaught (in promise) TypeError: Cannot read property 'isProxied' of undefined
    at index-cb5c04e4.js:1310
    at step (index-cb5c04e4.js:45)
    at Object.next (index-cb5c04e4.js:26)
    at fulfilled (index-cb5c04e4.js:17)
```

**Comment by SolarKing** [comment]
just noticed the latest commit in this repo: https://github.com/BlinkID/blinkid-in-browser/commit/6971f20b39fdcb07d72dcf61a1f76bd6737a3bfb#diff-7934f04055e569c5934c8f4dbff4270d4f55afba07e4dd51b48827ce7d8f9c1eR250

Looks like y'all are forcing "BASIC" to run.

We added that to our code and we got a bit further along.

Seems tho we need to update our dev evaluation license since it expired, but we will push out to prod and cross our fingers :crossed_fingers: since that license is still good

**Comment by SolarKing** [comment]
So it looks like its sorta working, the wasm files load but we are getting issues getting the `faceImage` and `fullDocumentImage`

Using the Chrome Debugger, this is a subset of the results we got back from scanning the ID:

```
employer: ""
faceImage: {
  encodedImage: Uint8Array []
  rawImage: null
  __proto__: Object
}
firstName: "OMITTED"
fullDocumentImage:{
  encodedImage: Uint8Array []
  rawImage: null
  __proto__: Object
}
fullName: ""
```

not sure if this is because we are using a newer version

**Comment by SolarKing** [comment]
Bump on this since it's Monday

**Comment by vjekoart** [comment]
Hi @SolarKing,

Thank you for the detailed report.

## WebAssembly bundles

Regarding the problem with `engine-location`. In the latest version, we introduced two new WebAssembly builds with improved performance.

From version 5.11.0, SDK will automatically detect which WebAssembly bundle to load based on the browser features. Every bundle type should work out of the box, except `advanced-threads` bundle. This bundle requires a proper setup on the server-side. That is, WebAssembly files should be served with COOP and COEP headers (more information can be found in the [documentation](https://github.com/BlinkID/blinkid-in-browser/blob/master/README.md#deployment-of-wasm-files)).

Unfortunately, unpkg.com doesn't provide the aforementioned headers, and therefore it's not possible to load the most performant WebAssembly bundle from that location. That is why we added `el.wasmType = "BASIC";` to all public examples. We're going to change that once we deploy our own CDN for WebAssembly files.

It's important to note that unpkg.com and our own CDN for WebAssembly are **not suitable** for production usage.

We're aware that it's a miss from our side that we didn't mention this change strongly enough in the release notes.

## Face and document image

We haven't changed the logic behind the extraction of images from a document. Could you provide us with a sample code that you're using to initialize and configure the UI component you're using?

Also, always check whether the required fields are present in the results object before using them. It's quite possible that scanning of specific fields was unsuccessful due to various reasons like covering a part of the document with a finger.

---

Sincerely,
Vjekoslav
