### ISSUE TITLE
support dual file for front/back file upload

### ISSUE THREAD

**Issue by ramarro123** [BlinkID/blinkid-in-browser#72]
Selecting combined id scan, make the upload file becaming disable. 

i would like to be able to load 2 distinct files and re-enable the file upload functionality for combinedscan

**Comment by AngTim** [comment]
Hello Ramarro,

I hope you're doing well and staying safe.
If you are interested in such a feature, please try out the demo example here:
[https://codepen.io/microblink/pen/MWboMrr](url)
Also, you can try and implement the combined-file example from our examples directory. 
[https://github.com/BlinkID/blinkid-in-browser/tree/master/examples/combined-file](url)

Please try them out and let us know if you have any additional questions.

Kind regards
Web Support Associate
Microblink LTD
