### ISSUE TITLE
No value for issuingAuthority for US NC DL scanned using Combined Recognizer 

### ISSUE THREAD

**Issue by gfbeqs** [BlinkID/blinkid-in-browser#74]
I'm using a combined recognizer to scan the front and back of my NC DL, but the issuingAuthority is an empty string (in the result root, but also in the frontViz, backViz and barcode properties.  Within the barcode.barcodeData.stringData I see the AAMVA Issuer Identification Number of 636004, so it should be simple to lookup the issuing authority.  I don't see another value 

Having the issuing authority for a DL is very important.

Passport scanning does propery extract a value for the issuingAuthority.
The issuingAuthority at the root level has the same value as frontViz.issuingAuthority, and there are slightly different (but more useful) value for mrz.issuer and mrz.issuerName

**Comment by gfbeqs** [comment]
Maybe classInfo contains this information?

**Comment by AngTim** [comment]
Hi Gfbeqs,

Thank you for your inquiry.
On the following link, you can find all the class info fields that are extracted: [https://github.com/BlinkID/blinkid-in-browser/blob/f1ce49fffc44e9aa70cc37245b2092a93e663f4c/src/Recognizers/BlinkID/Generic/ClassInfo.ts](url)
Could you please provide us with additional information regarding the issue? Which version of the NC DL are you scanning in your use case, and in which year was it issued? 
Also, on the following link are listed all the document fields that are extracted from the NC DL on the front and back of the document:
[https://github.com/BlinkID/blinkid-in-browser/blob/v5.16.0/docs/BlinkIDDocumentFields.md](url)

If you have any additional questions or issues, feel free to contact us.

Kind regards,
Angelo
Web Support Associate
Microblink LTD

**Comment by gfbeqs** [comment]
The AAMVA Version number is 08.
The Jurisdiction Version Number is 00.
The Card Revision Date (DDB field) is 10/24/2014.
The DL was issued in 2020.

May I suggest adding standard region codes to the ClassInfo data structure, similar to the isoNumericCountryCode, isoAlpha2CountryCode, and  isoAlpha3CountryCode? I'd suggest ISO-3166-2.
As it stands now we have to lookup your proprietary Region number in ClassInfo.ts to understand the value.

**Comment by AngTim** [comment]
Hello Qfbeqs,

Thank you for the additional information and the suggestion; I will forward it internally. 
Another issue with the said DL is that it is still not supported by our SDK, but you can follow our SDK releases on the following link with all the new supported documents: [https://github.com/BlinkID/blinkid-in-browser/releases](URL)

Please let us know if there is anything else we can assist you with.

Kind regards,
Angelo 
Web Support Associate
Microblink LTD
