### ISSUE TITLE
How we can save SuccessFrameGrabberRecognizer Result to a file in javascript (BlinkID/blinkid-in-browser)

### ISSUE THREAD

**Issue by volvicoasis** [BlinkID/blinkid-in-browser#75]
How we can save SuccessFrameGrabberRecognizer Result to a file in javascript (BlinkID/blinkid-in-browser) ?
We receive an arraybuffer but we didnt manage to save it to google cloud storage or a file.

**Comment by AngTim** [comment]
Hello Jacques,

I hope you're doing well and staying safe.
Could you please provide us with additional information regarding your inquiry?
  - What is the format in which you want to save the SuccessFrameGrabberRecognizer Results in a file?
  - Could you give us more information about the exact scanning flow that you are trying to achieve in your use case?

If you have any additional information or issues, feel free to contact us.


Kind regards,
Angelo Timko
Web Support Associate
Microblink LTD
