### ISSUE TITLE
Updating In-browser-sdk version from 5.16.0 to 5.18.0

### ISSUE THREAD

**Issue by DilipV2503** [BlinkID/blinkid-in-browser#82]
**Hello, 
I updated the version of in-browser-sdk from 5.16.0 to 5.18.0 and getting the below error**
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/83951998/183588134-c26292fb-c594-4e78-a50b-46034d378fd4.png)

**and, The below code , I am using**
![image](https://user-images.githubusercontent.com/83951998/183579980-6ab839e9-76f4-4533-9458-fdae66fdde4c.png)

**Please let me know what I am missing also I have checked the document and it is setting the workerLocation also for the new version**

**Note:- Is it necessary to set workerLocation Path?
 If yes then what should be the path**

**Comment by AngTim** [comment]
Hello Dilip,

I hope you're doing well.
Thank you for the inquiry and the code snippet. Can you try to access the file that is throwing the 404 error via your browser?
There is no need currently to modify the workerLocation path.

Let us know if you are able to access the file, and feel free to contact us if you have any additional questions or issues.


Kind regards,
Angelo
Web Support Associate
Microblink LTD

**Comment by DilipV2503** [comment]
Hello Angelo,

Yes, I am getting the 404 error when trying to access the URL which appears in the console.

Let me know if you need anything else.

Thanks!

**Comment by yasmeenokh** [comment]
Hello, I have also faced some problems when i updated i keep getting this error 
`BlinkIDWasmSDK.worker.min.js:1 Uncaught SyntaxError: Unexpected token '<' (at BlinkIDWasmSDK.worker.min.js:1:1)`
 
 I am using react and the resource folder is placed in the public folder

**Comment by AngTim** [comment]
The thread was inactive.
