### ISSUE TITLE
VIDEO_RECOGNIZER_ELEMENT_MISSING not able to open camera

### ISSUE THREAD

**Issue by Julietteve** [BlinkID/blinkid-in-browser#85]
I am implementing  **@microblink/blinkid-in-browser-sdk 5.18.0** on a React JS project. I am componentizing the codepen example provided. As I press SCAN, the error below appears on the console.

![image](https://user-images.githubusercontent.com/52335847/191758632-c8b0df26-c623-4629-a430-5386e8bc6eec.png)

Also tried implementing`<blinkid-in-browser ref={el}></blinkid-in-browser>`  but the document scanner is not as good as the example provided at CodePen.

What am I doing wrong ?

Thanks in advance.

**Comment by Julietteve** [comment]
Solved. The issue was related to a state management with React.

**Comment by AngTim** [comment]
Hi Julietteve,

Thank you for the feedback.
I am glad you managed to get to the solution, and I apologize for the lack of support.

Feel free to contact us if you encounter any new issues or have additional questions.

Kind regards,
Angelo
Web Support Specialist
Microblink LTD
